services:
  postgres:
    container_name: enzo-klassmatt-test-postgres
    image: postgres
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
  backend:
    container_name: enzo-klassmatt-test-backend
    image: enzo-klassmatt-test-backend
    build:
      context: todo-backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      DB_USER: postgres
      DB_HOST: host.docker.internal
      DB_NAME: todolist
      DB_PASSWORD: root
    volumes:
      - '.:/backend-app'
      - '/backend-app/node_modules'
    command: yarn start
    depends_on:
      - postgres
  frontend:
    container_name: enzo-klassmatt-test-frontend
    image: enzo-klassmatt-test-frontend
    build:
      context: todo-frontend
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - '.:/frontend-app'
      - '/frontend-app/node_modules'
    command: yarn start
