services:
  postgres:
    image: postgres
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
